// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ9Mt5F7h3jmNA4Utx8Aga1pBTmm5R15s',
    appId: '1:114566651471:web:dc9fe307c177e22d12d43a',
    messagingSenderId: '114566651471',
    projectId: 'ktc-app-54116',
    authDomain: 'ktc-app-54116.firebaseapp.com',
    storageBucket: 'ktc-app-54116.appspot.com',
    measurementId: 'G-BVBSLETHWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsHKuq1hGHc1IwGRvp9u0cfp6YYBn6ASM',
    appId: '1:114566651471:android:cbe55e09dea0071a12d43a',
    messagingSenderId: '114566651471',
    projectId: 'ktc-app-54116',
    storageBucket: 'ktc-app-54116.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMs1EsaoFIOe-UkUPqytMzRv8TrMTwBro',
    appId: '1:114566651471:ios:f532a8cb6b0b09f312d43a',
    messagingSenderId: '114566651471',
    projectId: 'ktc-app-54116',
    storageBucket: 'ktc-app-54116.appspot.com',
    iosClientId:
        '114566651471-tq80ligaopv4g4mjjd7f7395770qigj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ktcApp',
  );
}
